services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8675:3000"
    command: uvicorn app:app --host 0.0.0.0 --port 3000

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30